version: "3"
services:
  web:
    image: ebm1718travis/sagg:latest
    depends_on:
      - mongodb
    environment:
      - APP_PORT=4000
      - MONGODB_URI=mongodb://mongodb/sagg
    networks:
      local:
      ebm-filrouge:
        aliases:
          - sagg
  mongodb:
    image: mongo
    networks:
      - local
networks:
  local:
  ebm-filrouge:
    external: true 
