version: "3"
services:
  web:
    image: ebm1718travis/sagg:latest
    environment:
      - MONGODB_URI=mongodb://mongodb/sagg
    networks:
      local:
      ebm-filrouge:
        aliases:
          - sagg
  mongodb:
    image: mongo
    networks:
      - local
    volumes:
      - mongo-volume:/data/db
networks:
  local:
  ebm-filrouge:
    external: true
volumes:
  mongo-volume:
